# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-15 18:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='description',
            name='course_id',
        ),
        migrations.AddField(
            model_name='course',
            name='description',
            field=models.TextField(default=' ', max_length=1000),
        ),
        migrations.DeleteModel(
            name='Description',
        ),
    ]
