# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-15 23:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses_app', '0003_auto_20170315_1949'),
    ]

    operations = [
        migrations.RenameField(
            model_name='description',
            old_name='course_id',
            new_name='course',
        ),
    ]
